services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html  # This is the magic: mounts your local folder
    environment:
      - APP_ENV=local
    depends_on:
      - mspguild-db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mspguild-db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mspguild
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d # Auto-loads your schema on start